name: Daily Alphabot Scrape

on:
  schedule:
    - cron: "0 3-4 * * *"   # 03:00 & 04:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: alphabot-daily
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25           # ← avoid exit code 124
    env:
      TZ: "Europe/Paris"
      WINDOW_HOURS: "24"
      # DAY_TZ: "Europe/Paris"    # uncomment if you want “today” relative to Paris

    steps:
      - uses: actions/checkout@v4

      # run-lock so we don't run twice the same day (Paris date)
      - name: Compute Paris date
        id: time
        run: echo "paris_date=$(TZ=Europe/Paris date +%F)" >> $GITHUB_OUTPUT

      - name: Check run-lock
        id: lock
        uses: actions/cache/restore@v4
        with:
          key: alphabot-runlock-${{ steps.time.outputs.paris_date }}
          path: .runlock
          restore-keys: |
            alphabot-runlock-

      - name: Setup Node
        if: steps.lock.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        if: steps.lock.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright browsers
        if: steps.lock.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Scrape
        if: steps.lock.outputs.cache-hit != 'true'
        run: node scraper.mjs
        env:
          MAX_ROWS: "25"          # cap amount to click
          CALENDAR_URL: "https://www.alphabot.app/calendar"

      # upload *even on failure* so we can debug
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alphabot-${{ github.run_id }}
          path: |
            out/**
            traces/**
            playwright-*.png
            debug.log

      - name: Save run-lock (mark done for today)
        if: steps.lock.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: alphabot-runlock-${{ steps.time.outputs.paris_date }}
          path: .runlock
