name: Daily Alphabot Scrape

on:
  schedule:
    - cron: "30 6 * * *"   # 06:30 UTC ~ 08:30 Paris (été)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Scrape
        run: node scraper.mjs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alphabot-${{ github.run_id }}
          path: out/*
