name: Daily Alphabot Scrape

on:
  schedule:
    - cron: "0 3-4 * * *"        # 03:00 & 04:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: alphabot-daily
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      TZ: "Europe/Paris"
      WINDOW_HOURS: "24"
      # DAY_TZ: "Europe/Paris"   # uncomment if you want “today” in Paris TZ

    steps:
      - uses: actions/checkout@v4

      - name: Compute Paris date
        id: time
        run: echo "paris_date=$(TZ=Europe/Paris date +%F)" >> $GITHUB_OUTPUT

      - name: Check run-lock
        id: lock
        uses: actions/cache/restore@v4
        with:
          key: alphabot-runlock-${{ steps.time.outputs.paris_date }}
          path: .runlock
          restore-keys: |
            alphabot-runlock-

      - name: Setup Node
        if: steps.lock.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        if: steps.lock.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright browsers
        if: steps.lock.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Scrape
        if: steps.lock.outputs.cache-hit != 'true'
        env:
          MAX_ROWS: "25"
          CALENDAR_URL: "https://www.alphabot.app/calendar"
          DEBUG: "pw:api"         # verbose Playwright logs in debug.log
        run: node scraper.mjs

      # Always create folders & placeholders so artifacts upload never says "no files"
      - name: Ensure artifacts folder (always)
        if: always()
        run: |
          mkdir -p out traces
          [ -f out/EMPTY.txt ] || echo "no data (failure or zero items)" > out/EMPTY.txt
          [ -f traces/EMPTY.txt ] || echo "no trace" > traces/EMPTY.txt
          [ -f debug.log ] || echo "no debug log" > debug.log

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alphabot-${{ github.run_id }}
          path: |
            out/**
            traces/**
            playwright-*.png
            debug.log

      - name: Save run-lock (mark done for today)
        if: steps.lock.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: alphabot-runlock-${{ steps.time.outputs.paris_date }}
          path: .runlock
