name: Daily Alphabot Scrape

on:
  schedule:
    - cron: "0 3-4 * * *"   # 03:00 et 04:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Paris"
      # Pas de filtre par défaut -> évite les CSV vides
      ONLY_TODAY: "false"
      DAY_TZ: "Europe/Paris"
      MAX_ROWS: "20"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Scrape
        run: node scraper.mjs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alphabot-${{ github.run_id }}
          path: |
            *.csv
            *.json
